FROM node:24 AS test-stage
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run test

FROM test-stage AS build-stage
ENV VITE_BACKEND_URL=/api
RUN npm run build


FROM nginx:1.29-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html