services:
  app:
    image: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
      - VITE_BACKEND_URL=/api
    container_name: todo-front-container  
  backend:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-backend-container
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
     - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
     - mongo_data:/data/db
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend
volumes:
  mongo_data:
  redis_data: